import { existsSync, readFileSync, statSync } from 'node:fs';
import { defineCommand } from 'citty';
import consola from 'consola';
import { colors } from 'consola/utils';
import { basename, dirname } from 'pathe';
import { type Found, type FoundKind, findGitignores } from '../discover.ts';
import { DIVIDER, stacksLine } from '../gitignore/markers.ts';
import { parse } from '../gitignore/parse.ts';
import { reconcile } from '../gitignore/reconcile.ts';
import { stackOrder } from '../templates/index.ts';

type Row = {
  name: string;
  kind: FoundKind;
  file: string;
  /** Patterns in the file before reconciling: no blanks, no comments. */
  before: number;
  /** Patterns still in the free zone after every stack was applied. */
  after: number;
  leftovers: string[];
};

type Report = {
  files: Row[];
  totals: { before: number; after: number; covered: number; percent: number };
  /** Stubs left unmeasured, and why. */
  skipped: { label: string; kind: FoundKind }[];
  /** Every leftover pattern with the files that carry it, most common first. */
  leftovers: { pattern: string; files: string[] }[];
};

const isPattern = (line: string): boolean => {
  const t = line.trim();
  return t !== '' && !t.startsWith('#');
};

/**
 * Measure one file against every stack this binary ships.
 *
 * The point is not to rewrite anything — it is to answer "what would still be
 * left over if this repo declared everything?", because that remainder is what
 * decides whether a stack is missing or the lines are genuinely project rules.
 */
function auditFile(found: Found, label: string): Row {
  const file = found.file;
  const text = readFileSync(file, 'utf8');
  const before = text.split('\n').filter(isPattern).length;

  const doc = parse(text);
  const all = stackOrder();
  const result = reconcile({
    ...doc,
    header: [stacksLine(all), DIVIDER],
    hasRegion: true
  });
  const leftovers = result.document.freeZone
    .filter(isPattern)
    .map((l) => l.trim());

  return {
    name: label,
    kind: found.kind,
    file,
    before,
    after: leftovers.length,
    leftovers
  };
}

export const auditCommand = defineCommand({
  meta: {
    name: 'audit',
    description:
      'Measure how much of one or more repos the shipped stacks already cover'
  },
  args: {
    dirs: {
      type: 'positional',
      description: 'Repository directories (default: the current one)',
      required: false,
      default: '.'
    },
    'min-files': {
      type: 'string',
      description: 'Only list leftovers carried by at least this many files',
      default: '1'
    },
    recursive: {
      type: 'boolean',
      description:
        'Also measure .gitignore files below each directory, skipping build and dependency output',
      alias: 'r',
      default: false
    },
    'include-stubs': {
      type: 'boolean',
      description:
        'Measure framework stubs too, instead of listing them as skipped',
      default: false
    },
    json: {
      type: 'boolean',
      description: 'Emit a machine-readable JSON report',
      default: false
    }
  },
  run({ args }) {
    const raw = args._ && args._.length > 0 ? args._ : [args.dirs];
    const dirs = [
      ...new Set(
        raw.filter((d): d is string => typeof d === 'string' && d !== '')
      )
    ].filter((dir) => {
      if (!existsSync(dir) || !statSync(dir).isDirectory()) {
        consola.warn(`Not a directory, skipped: ${dir}`);
        return false;
      }
      return true;
    });

    if (dirs.length === 0) {
      consola.error('Nothing to audit.');
      process.exitCode = 1;
      return;
    }

    const targets: { found: Found; label: string }[] = [];
    const skipped: { label: string; kind: FoundKind }[] = [];
    for (const dir of dirs) {
      const hits = findGitignores(dir, { recursive: args.recursive });
      if (hits.length === 0) {
        consola.warn(`No .gitignore, skipped: ${dir}`);
        continue;
      }
      for (const found of hits) {
        // One directory reads as its own name; a recursive sweep needs the
        // path, or two `apps/*/.gitignore` rows are indistinguishable.
        const label =
          found.relative === '.gitignore'
            ? basename(dir)
            : `${basename(dir)}/${dirname(found.relative)}`;
        // A stub exists to hold an empty directory or is generated by a
        // framework. Measuring it against the stacks would report a leftover
        // for every line and suggest changing a file nobody owns.
        if (
          !args['include-stubs'] &&
          (found.kind === 'keeper' || found.kind === 'framework')
        ) {
          skipped.push({ label, kind: found.kind });
          continue;
        }
        targets.push({ found, label });
      }
    }

    if (targets.length === 0) {
      consola.error('Nothing to audit.');
      process.exitCode = 1;
      return;
    }

    const files = targets
      .map(({ found, label }) => auditFile(found, label))
      .sort((a, b) => b.before - a.before);
    const before = files.reduce((n, f) => n + f.before, 0);
    const after = files.reduce((n, f) => n + f.after, 0);

    const carriers = new Map<string, string[]>();
    for (const row of files) {
      for (const line of row.leftovers) {
        const seen = carriers.get(line);
        if (seen) seen.push(row.name);
        else carriers.set(line, [row.name]);
      }
    }
    const minFiles = Math.max(1, Number(args['min-files']) || 1);
    const leftovers = [...carriers]
      .map(([pattern, names]) => ({ pattern, files: names }))
      .filter((l) => l.files.length >= minFiles)
      .sort(
        (a, b) =>
          b.files.length - a.files.length || a.pattern.localeCompare(b.pattern)
      );

    const report: Report = {
      files,
      totals: {
        before,
        after,
        covered: before - after,
        percent:
          before === 0
            ? 100
            : Math.round(((before - after) / before) * 1000) / 10
      },
      leftovers,
      skipped
    };

    if (args.json) {
      process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
      return;
    }

    const width = Math.max(...files.map((f) => f.name.length), 4);
    consola.log(
      `  ${colors.dim('repo'.padEnd(width))} ${colors.dim('before')}  ${colors.dim('left')}`
    );
    for (const row of files) {
      consola.log(
        `  ${row.name.padEnd(width)} ${String(row.before).padStart(6)}  ${String(row.after).padStart(4)}`
      );
    }
    consola.log(
      `\n  ${colors.bold(`${report.totals.before} patterns → ${report.totals.after} left`)} ${colors.dim(`(${report.totals.percent}% covered by the shipped stacks)`)}`
    );

    if (skipped.length > 0) {
      const keepers = skipped.filter((s) => s.kind === 'keeper').length;
      const framework = skipped.length - keepers;
      const parts = [
        keepers > 0 ? `${keepers} directory keeper(s)` : '',
        framework > 0 ? `${framework} framework stub(s)` : ''
      ].filter(Boolean);
      consola.log(
        `\n  ${colors.dim(`skipped ${parts.join(' and ')} — generated, and owned by the framework. --include-stubs measures them anyway.`)}`
      );
    }

    if (leftovers.length > 0) {
      consola.log(
        `\n  ${colors.dim(`leftovers carried by ${minFiles}+ file(s), most common first`)}`
      );
      for (const { pattern, files: names } of leftovers) {
        consola.log(
          `  ${String(names.length).padStart(3)}x  ${pattern}  ${colors.dim(names.slice(0, 4).join(', ') + (names.length > 4 ? ', …' : ''))}`
        );
      }
    }
  }
});
