import { existsSync, readFileSync, readdirSync, type Dirent } from 'node:fs';
import { join, relative } from 'pathe';
import { currentTemplate, stackOrder } from './templates/index.ts';

/**
 * Why a `.gitignore` found below the root is what it is.
 *
 * - `managed` — carries a gitignore-sync region already.
 * - `keeper` — exists only to hold an otherwise empty directory in git
 *   (`*` plus `!.gitignore`). Generated by a framework, owned by it, and
 *   nothing this tool should touch.
 * - `framework` — a stub at a path a framework owns (Laravel's `storage/`,
 *   husky's `_`). Same verdict, different evidence.
 * - `plain` — an ordinary `.gitignore`. The only kind worth a decision.
 */
export type FoundKind = 'managed' | 'keeper' | 'framework' | 'plain';

export type Found = {
  /** Absolute path of the file. */
  file: string;
  /** Path relative to the root the scan started at. */
  relative: string;
  kind: FoundKind;
};

/**
 * Directory names never descended into, derived from the templates themselves.
 *
 * A stack that ignores a build directory is exactly a stack whose output must
 * not be scanned, so the list maintains itself: adding `turborepo` added
 * `.turbo` here with it. Hand-maintaining a second list would guarantee the two
 * drift.
 */
export function skipDirectories(): Set<string> {
  const skip = new Set(['.git']);
  for (const stack of stackOrder()) {
    for (const line of currentTemplate(stack)?.lines ?? []) {
      addDirectoryName(skip, line);
    }
  }
  return skip;
}

/**
 * Add a gitignore pattern to a skip set, if and only if it names a plain
 * directory. Only a bare name qualifies: no globs, and no path either. Taking
 * the last segment of `/public/build` or `/public/storage` would skip every
 * `build/` and `storage/` in the tree — including the Laravel stubs a
 * recursive scan is supposed to find and label, not hide.
 */
function addDirectoryName(skip: Set<string>, line: string): void {
  const raw = line.trim();
  if (raw === '' || raw.startsWith('#') || raw.startsWith('!')) return;
  const name = raw.replace(/^\/+/, '').replace(/\/+$/, '');
  if (name === '' || /[*?[\]]/.test(name) || name.includes('/')) return;
  skip.add(name);
}

/**
 * What a `.gitignore` says not to look at. A directory the repository itself
 * ignores is generated — a mutation-testing sandbox, a build tree, a vendored
 * copy — so a scan has no business walking into it, exactly as git has none.
 * This is what catches the output of tools no template knows about.
 */
export function ignoredDirectories(text: string): Set<string> {
  const skip = new Set<string>();
  for (const line of text.split('\n')) addDirectoryName(skip, line);
  return skip;
}

/**
 * Directory paths a framework generates and owns. Matched against any position
 * in the path, not just its start, so a package inside a monorepo
 * (`services/core/storage/logs`) is recognised as readily as a root one.
 */
const FRAMEWORK_PATHS = [
  'storage', // Laravel
  'bootstrap/cache', // Laravel
  '.husky' // husky
];

const underFrameworkPath = (rel: string): boolean => {
  const dir = rel.slice(0, rel.lastIndexOf('/') + 1);
  return FRAMEWORK_PATHS.some(
    (p) => dir === `${p}/` || dir.startsWith(`${p}/`) || dir.includes(`/${p}/`)
  );
};

/**
 * A file whose whole job is keeping an empty directory in git: it ignores
 * everything and un-ignores itself. Recognised by content, not by path, so it
 * holds for any framework that uses the idiom.
 */
export function isDirectoryKeeper(text: string): boolean {
  const lines = text
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l !== '' && !l.startsWith('#'));
  if (lines.length === 0) return false;
  const ignoresEverything = lines.some((l) => l === '*' || l === '*.*');
  const keepsItself = lines.some((l) => l === '!.gitignore');
  return ignoresEverything && keepsItself;
}

function classify(file: string, rel: string): FoundKind {
  let text: string;
  try {
    text = readFileSync(file, 'utf8');
  } catch {
    return 'plain';
  }
  if (/^#\s*region\s+gitignore-sync\s*$/m.test(text)) return 'managed';
  if (isDirectoryKeeper(text)) return 'keeper';
  if (underFrameworkPath(rel)) return 'framework';
  return 'plain';
}

/**
 * Every `.gitignore` at or below `root`.
 *
 * Non-recursive returns at most the root's own file, which is what every
 * command does by default — a repository has one managed region, and walking a
 * tree to find that out would be waste.
 */
export function findGitignores(
  root: string,
  options: { recursive?: boolean; maxDepth?: number } = {}
): Found[] {
  const skip = skipDirectories();
  const found: Found[] = [];
  const maxDepth = options.maxDepth ?? 12;

  const walk = (dir: string, depth: number, inherited: Set<string>): void => {
    let entries: Dirent[];
    try {
      entries = readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    let here = inherited;
    for (const entry of entries) {
      if (entry.name === '.gitignore' && entry.isFile()) {
        const file = join(dir, '.gitignore');
        const rel = relative(root, file) || '.gitignore';
        found.push({ file, relative: rel, kind: classify(file, rel) });
        // What this file ignores applies to everything below it, so it joins
        // the skip set for this subtree and every subtree under it.
        try {
          here = new Set([
            ...here,
            ...ignoredDirectories(readFileSync(file, 'utf8'))
          ]);
        } catch {
          // Unreadable: carry on with what we already had.
        }
      }
    }
    if (!options.recursive || depth >= maxDepth) return;
    for (const entry of entries) {
      if (!entry.isDirectory() || entry.isSymbolicLink()) continue;
      if (here.has(entry.name)) continue;
      const child = join(dir, entry.name);
      // A directory holding its own `.git` is a separate repository — a
      // submodule, a vendored checkout, or an agent worktree. Its `.gitignore`
      // belongs to that repo and would otherwise be counted here, several
      // times over.
      if (existsSync(join(child, '.git'))) continue;
      walk(child, depth + 1, here);
    }
  };

  walk(root, 0, skip);
  return found.sort((a, b) => a.relative.localeCompare(b.relative));
}
